<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TypingPet</AssemblyName>
    <ApplicationIcon Condition="'$(ShareBuild)' != 'true'">TypingPet.Personal.ico</ApplicationIcon>
    <RootNamespace>TypingPet</RootNamespace>
    <Version>0.7.0</Version>
    <FileVersion>0.7.0.0</FileVersion>
    <InformationalVersion>Ver.0.7</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>NNNNNTK</Authors>
    <Company>NNNNNTK</Company>
    <Copyright>Copyright © 2026 NNNNNTK</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AntdUI" Version="2.4.12" />
  </ItemGroup>
</Project>
