<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TypingPet</AssemblyName>
    <RootNamespace>TypingPet</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AntdUI" Version="2.4.12" />
  </ItemGroup>
</Project>
